import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as React from "react";
import HomePage from "./HomePage";
import Navbar from "../components/shared/Navbar";
import { collection, addDoc, getDocs } from "firebase/firestore";
import { app, database } from "../firebaseConfig";
import Project from "./project/[id]";
export default function Home() {
  const dbInstance = collection(database, "projects");
  const getProjects = () => {
    getDocs(dbInstance).then((data) => {
      console.log(data);
    });
  };

  React.useEffect(() => {
    getProjects();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Solutack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main >
        <HomePage />
      </main>
    </div>
  );
}
